CREATE TABLE categories
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE chat_widget_messages
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    session_id BIGINT                                  NOT NULL,
    sender     VARCHAR(255)                            NOT NULL,
    text       TEXT                                    NOT NULL,
    intent     VARCHAR(64),
    metadata   JSONB                                   NOT NULL,
    CONSTRAINT pk_chat_widget_messages PRIMARY KEY (id)
);

CREATE TABLE chat_widget_session
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    user_id    BIGINT                                  NOT NULL,
    started_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    ended_at   TIMESTAMP WITHOUT TIME ZONE,
    context    JSONB                                   NOT NULL,
    CONSTRAINT pk_chat_widget_session PRIMARY KEY (id)
);

CREATE TABLE company_preferred_categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    company_id  BIGINT                                  NOT NULL,
    category_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_company_preferred_categories PRIMARY KEY (id)
);

CREATE TABLE company_profiles
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    user_id      BIGINT                                  NOT NULL,
    company_name VARCHAR(255),
    industry_id  BIGINT,
    description  TEXT,
    website_url  VARCHAR(255),
    country_id   BIGINT,
    min_budget   DECIMAL(12, 2)                          NOT NULL,
    max_budget   DECIMAL(12, 2)                          NOT NULL,
    CONSTRAINT pk_company_profiles PRIMARY KEY (id)
);

CREATE TABLE conversation_participants
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    conversation_id      BIGINT                                  NOT NULL,
    user_id              BIGINT                                  NOT NULL,
    role_in_conversation VARCHAR(255)                            NOT NULL,
    joined_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_muted             BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_conversation_participants PRIMARY KEY (id)
);

CREATE TABLE conversations
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    type               VARCHAR(255)                            NOT NULL,
    offer_id           BIGINT,
    created_by_user_id BIGINT,
    last_message_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_conversations PRIMARY KEY (id)
);

CREATE TABLE countries
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255)                            NOT NULL,
    code       VARCHAR(2)                              NOT NULL,
    CONSTRAINT pk_countries PRIMARY KEY (id)
);

CREATE TABLE creator_audience_age
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    creator_id BIGINT                                  NOT NULL,
    age_begin  INTEGER                                 NOT NULL,
    age_end    INTEGER                                 NOT NULL,
    percentage DECIMAL(5, 2)                           NOT NULL,
    CONSTRAINT pk_creator_audience_age PRIMARY KEY (id)
);

CREATE TABLE creator_audience_geo
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    creator_id BIGINT                                  NOT NULL,
    country_id BIGINT                                  NOT NULL,
    percentage DECIMAL(5, 2)                           NOT NULL,
    CONSTRAINT pk_creator_audience_geo PRIMARY KEY (id)
);

CREATE TABLE creator_platforms
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    creator_id      BIGINT                                  NOT NULL,
    platform        VARCHAR(255),
    profile_url     VARCHAR(255),
    followers_count INTEGER,
    avg_views       INTEGER,
    CONSTRAINT pk_creator_platforms PRIMARY KEY (id)
);

CREATE TABLE creator_profiles
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    user_id             BIGINT                                  NOT NULL,
    display_name        VARCHAR(255)                            NOT NULL,
    bio                 TEXT,
    primary_category_id BIGINT                                  NOT NULL,
    followers_count     INTEGER                                 NOT NULL,
    avg_views           INTEGER                                 NOT NULL,
    engagement_rate     DECIMAL(5, 2)                           NOT NULL,
    contact_email       VARCHAR(255),
    CONSTRAINT pk_creator_profiles PRIMARY KEY (id)
);

CREATE TABLE email_confirmation_codes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    code       VARCHAR(255)                            NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    used       BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_email_confirmation_codes PRIMARY KEY (id)
);

CREATE TABLE industries
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_industries PRIMARY KEY (id)
);

CREATE TABLE match_results
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    offer_id          BIGINT                                  NOT NULL,
    creator_id        BIGINT                                  NOT NULL,
    similarity_score  DECIMAL(5, 4)                           NOT NULL,
    performance_score DECIMAL(5, 4)                           NOT NULL,
    risk_penalty      DECIMAL(5, 4)                           NOT NULL,
    final_score       DECIMAL(5, 4)                           NOT NULL,
    explanation       TEXT                                    NOT NULL,
    breakdown         JSONB                                   NOT NULL,
    CONSTRAINT pk_match_results PRIMARY KEY (id)
);

CREATE TABLE message_attachments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    message_id BIGINT                                  NOT NULL,
    type       VARCHAR(255)                            NOT NULL,
    url        VARCHAR(1024),
    file_name  VARCHAR(255),
    CONSTRAINT pk_message_attachments PRIMARY KEY (id)
);

CREATE TABLE messages
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    conversation_id BIGINT                                  NOT NULL,
    sender_user_id  BIGINT                                  NOT NULL,
    message_type    VARCHAR(255)                            NOT NULL,
    body            TEXT                                    NOT NULL,
    read_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_messages PRIMARY KEY (id)
);

CREATE TABLE offer_risk_analysis
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    offer_id          BIGINT                                  NOT NULL,
    risk_score        DECIMAL(4, 3)                           NOT NULL,
    risk_label        VARCHAR(255)                            NOT NULL,
    moderation_status VARCHAR(255)                            NOT NULL,
    reasons           JSONB                                   NOT NULL,
    CONSTRAINT pk_offer_risk_analysis PRIMARY KEY (id)
);

CREATE TABLE offer_target_countries
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    offer_id   BIGINT                                  NOT NULL,
    country_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_offer_target_countries PRIMARY KEY (id)
);

CREATE TABLE offers
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    company_id          BIGINT                                  NOT NULL,
    title               VARCHAR(255)                            NOT NULL,
    description         TEXT                                    NOT NULL,
    category_id         BIGINT                                  NOT NULL,
    budget              DECIMAL(12, 2)                          NOT NULL,
    currency            VARCHAR(3)                              NOT NULL,
    target_min_age      INTEGER                                 NOT NULL,
    target_max_age      INTEGER                                 NOT NULL,
    campaign_start_date date,
    campaign_end_date   date,
    status              VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_offers PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    role       VARCHAR(255),
    status     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE categories
    ADD CONSTRAINT uc_categories_name UNIQUE (name);

ALTER TABLE company_profiles
    ADD CONSTRAINT uc_company_profiles_user UNIQUE (user_id);

ALTER TABLE countries
    ADD CONSTRAINT uc_countries_code UNIQUE (code);

ALTER TABLE countries
    ADD CONSTRAINT uc_countries_name UNIQUE (name);

ALTER TABLE creator_profiles
    ADD CONSTRAINT uc_creator_profiles_user UNIQUE (user_id);

ALTER TABLE email_confirmation_codes
    ADD CONSTRAINT uc_email_confirmation_codes_user UNIQUE (user_id);

ALTER TABLE industries
    ADD CONSTRAINT uc_industries_name UNIQUE (name);

ALTER TABLE offer_risk_analysis
    ADD CONSTRAINT uc_offer_risk_analysis_offer UNIQUE (offer_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE chat_widget_messages
    ADD CONSTRAINT FK_CHAT_WIDGET_MESSAGES_ON_SESSION FOREIGN KEY (session_id) REFERENCES chat_widget_session (id);

ALTER TABLE chat_widget_session
    ADD CONSTRAINT FK_CHAT_WIDGET_SESSION_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE company_preferred_categories
    ADD CONSTRAINT FK_COMPANY_PREFERRED_CATEGORIES_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE company_preferred_categories
    ADD CONSTRAINT FK_COMPANY_PREFERRED_CATEGORIES_ON_COMPANY FOREIGN KEY (company_id) REFERENCES company_profiles (id);

ALTER TABLE company_profiles
    ADD CONSTRAINT FK_COMPANY_PROFILES_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES countries (id);

ALTER TABLE company_profiles
    ADD CONSTRAINT FK_COMPANY_PROFILES_ON_INDUSTRY FOREIGN KEY (industry_id) REFERENCES industries (id);

ALTER TABLE company_profiles
    ADD CONSTRAINT FK_COMPANY_PROFILES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE conversations
    ADD CONSTRAINT FK_CONVERSATIONS_ON_CREATED_BY_USER FOREIGN KEY (created_by_user_id) REFERENCES users (id);

ALTER TABLE conversations
    ADD CONSTRAINT FK_CONVERSATIONS_ON_OFFER FOREIGN KEY (offer_id) REFERENCES offers (id);

ALTER TABLE conversation_participants
    ADD CONSTRAINT FK_CONVERSATION_PARTICIPANTS_ON_CONVERSATION FOREIGN KEY (conversation_id) REFERENCES conversations (id);

ALTER TABLE conversation_participants
    ADD CONSTRAINT FK_CONVERSATION_PARTICIPANTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE creator_audience_age
    ADD CONSTRAINT FK_CREATOR_AUDIENCE_AGE_ON_CREATOR FOREIGN KEY (creator_id) REFERENCES creator_profiles (id);

ALTER TABLE creator_audience_geo
    ADD CONSTRAINT FK_CREATOR_AUDIENCE_GEO_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES countries (id);

ALTER TABLE creator_audience_geo
    ADD CONSTRAINT FK_CREATOR_AUDIENCE_GEO_ON_CREATOR FOREIGN KEY (creator_id) REFERENCES creator_profiles (id);

ALTER TABLE creator_platforms
    ADD CONSTRAINT FK_CREATOR_PLATFORMS_ON_CREATOR FOREIGN KEY (creator_id) REFERENCES creator_profiles (id);

ALTER TABLE creator_profiles
    ADD CONSTRAINT FK_CREATOR_PROFILES_ON_PRIMARY_CATEGORY FOREIGN KEY (primary_category_id) REFERENCES categories (id);

ALTER TABLE creator_profiles
    ADD CONSTRAINT FK_CREATOR_PROFILES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE email_confirmation_codes
    ADD CONSTRAINT FK_EMAIL_CONFIRMATION_CODES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE match_results
    ADD CONSTRAINT FK_MATCH_RESULTS_ON_CREATOR FOREIGN KEY (creator_id) REFERENCES creator_profiles (id);

ALTER TABLE match_results
    ADD CONSTRAINT FK_MATCH_RESULTS_ON_OFFER FOREIGN KEY (offer_id) REFERENCES offers (id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_CONVERSATION FOREIGN KEY (conversation_id) REFERENCES conversations (id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_SENDER_USER FOREIGN KEY (sender_user_id) REFERENCES users (id);

ALTER TABLE message_attachments
    ADD CONSTRAINT FK_MESSAGE_ATTACHMENTS_ON_MESSAGE FOREIGN KEY (message_id) REFERENCES messages (id);

ALTER TABLE offers
    ADD CONSTRAINT FK_OFFERS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE offers
    ADD CONSTRAINT FK_OFFERS_ON_COMPANY FOREIGN KEY (company_id) REFERENCES company_profiles (id);

ALTER TABLE offer_risk_analysis
    ADD CONSTRAINT FK_OFFER_RISK_ANALYSIS_ON_OFFER FOREIGN KEY (offer_id) REFERENCES offers (id);

ALTER TABLE offer_target_countries
    ADD CONSTRAINT FK_OFFER_TARGET_COUNTRIES_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES countries (id);

ALTER TABLE offer_target_countries
    ADD CONSTRAINT FK_OFFER_TARGET_COUNTRIES_ON_OFFER FOREIGN KEY (offer_id) REFERENCES offers (id);